---
title: "Psychometric Curve Fitting"
output: html_document
---
# Setup
```{r setup, warning=FALSE}
data <- read.csv('Long 98 final.csv')
library(tidyverse)

fit_curve <- function(.data) {
  # This function takes a data frame and fits a logistic curve
  glm(
    accuracy ~ 1 + Range,
    family = binomial("logit"),
    data = .data
  )
}

extract_estimates <- function(model) {
  # This function takes a logistic model and extracts
  # the psychometric curve indices
  coef <- unname(coef(model))
  
  tibble(
    B = 1 / coef[2],
    A = -B * coef[1],
    
    j75 = A - B * log(1 / 0.75 - 1),
    j25 = A - B * log(1 / 0.25 - 1),
    
    JND = (j75 - j25) / 2,
    PSE = A - B * log(1 / 0.50 - 1)
  )
}

add_predictions <- function(model, grid) {
  # This function returns predictions for grid according to the model
  grid$Y_hat <- predict(model, newdata = grid, type = "response")
  grid
}


```
# Fit
```{r data}
# For each subject / task, fit a logistic curve (*add Group*)
data_fits <- data |> 
  group_by(experimentname, subject,Group,regression) |> 
  summarise(
    FIT = list(fit_curve(.data = pick(everything())))
  ) |> 
  ungroup()

# For each subject / task, extract the psychometric curve indices 
data_params <- data_fits |> 
  mutate(
    map(FIT, extract_estimates) |> bind_rows()
  ) |> 
  select(-FIT)
```

Add predictions:

```{r warning=FALSE}
grid <- data.frame(Range = c(0, 15, 21, 27, 33, 39, 45))

# Make predictions
data_predictions <- data_fits |> 
  #add *Group*
  group_by(experimentname,subject,Group,regression) |> 
  reframe(
    add_predictions(FIT[[1]], grid))|> 
  ungroup() |> 
  left_join(data, by = c("experimentname", "subject", "Range","Group","regression"))
# *add Group*
```

# Save results

Add R2

```{r}
data_params2 <- data_predictions |> 
  group_by(experimentname, subject,Group,regression) |> 
  summarise(
    Rsq = cor(accuracy, Y_hat) ^ 2
  ) |> 
  ungroup() |> 
  left_join(data_params, by = join_by(experimentname, subject,Group,regression))
#*add Group*
write.csv(data_predictions, "full_data_with_predictions.csv")
write.csv(data_params2, "full_results.csv")
```

# Plot

```{r}
data_predictions <- read.csv("full_data_with_predictions.csv")

ggplot(data_predictions, aes(X)) +
  facet_grid(rows = vars(Group), 
             cols = vars(experimentname), 
             as.table = FALSE) +
  geom_segment(aes(xend = Range, y = accuracy, yend = Y_hat), alpha = 0.2) +
  geom_line(aes(y = Y_hat, group = subject), alpha = 0.2) +
  geom_point(aes(y = accuracy), alpha = 0.2, shape = 16) +
  stat_summary(aes(y = Y_hat), geom = "line", 
               color = "red", linewidth = 1) +
  geom_hline(yintercept = 0.5, linetype = "dashed", linewidth = 0.7) +
  coord_cartesian(ylim = c(0, 1)) +
  theme_bw()
```
```{r}
data_params2 <- read.csv("full_results.csv")

ggplot(data_params2, aes(Rsq)) +
  facet_grid(rows = vars(Group), 
             cols = vars(experimentname), 
             as.table = FALSE) +
  geom_histogram() +
  coord_cartesian(xlim = c(0, 1)) +
  theme_bw()

ggplot(data_params2, aes(JND)) +
  facet_grid(rows = vars(Group), 
             cols = vars(experimentname), 
             as.table = FALSE) +
  geom_histogram() +
  theme_bw()

ggplot(data_params2, aes(PSE)) +
  facet_grid(rows = vars(Group), 
             cols = vars(experimentname), 
             as.table = FALSE) +
  geom_histogram() +
  theme_bw()
```


```{r}
data_predictions <- read.csv("full_data_with_predictions.csv")

ggplot(data_predictions, aes(x = Range)) +
  facet_grid(rows = vars(Group), 
             cols = vars(regression,experimentname), 
             as.table = TRUE) +
  #geom_segment(aes(xend = Range, y = accuracy, yend = Y_hat), alpha = 0.2) +
  geom_line(aes(y = Y_hat, group = subject), alpha = 0.15) +
  geom_point(aes(y = accuracy), alpha = 0.1, shape = 20) +
  stat_summary(aes(y = Y_hat), geom = "line", color = "red", linewidth = 1) +
  geom_hline(yintercept = 0.5, linetype = "dashed", linewidth = 0.5) +
  coord_cartesian(ylim = c(0, 1)) +
  coord_fixed(ratio = 50)+
  theme_bw()
  ggsave(filename = "my_plot.png",width = 20,height = 20)



```
```{r}
data_params2 <- read.csv("full_results.csv")

# Rsq histogram
ggplot(data_params2, aes(x = Rsq)) +
  facet_grid(rows = vars(Group), 
             cols = vars(experimentname), 
             as.table = FALSE) +
  geom_histogram() +
  coord_cartesian(xlim = c(0, 1)) +
  theme_bw()

# JND histogram
ggplot(data_params2, aes(x = JND)) +
  facet_grid(rows = vars(Group), 
             cols = vars(experimentname), 
             as.table = FALSE) +
  geom_histogram() +
  theme_bw()

# PSE histogram
ggplot(data_params2, aes(x = PSE)) +
  facet_grid(rows = vars(Group), 
             cols = vars(experimentname), 
             as.table = FALSE) +
  geom_histogram() +
  theme_bw()

```

# Explantion 

The model we are fitting a 2 parameter mode (A, B):

$$
P = \frac{1}{1 + e^{-(X-A)/B}}
$$
We are doing this by fitting a logistic curve:

$$
P = \frac{1}{1 + e^{-(a + bX)}}
$$
And the converting:

$$
B = 1 / b \\
A = -aB
$$


#PsychoMetric Test  
```{r}
#psychometric plot for biasp

data_predictions <- read.csv("full_data_with_predictions.csv")

ggplot(data_predictions %>% filter(regression == "biasp"), aes(x = Range, y = Y_hat)) +facet_grid(rows = vars(Group), 
             cols = vars(regression,experimentname), 
             as.table = TRUE) +
  #geom_segment(aes(xend = Range, y = accuracy, yend = Y_hat), alpha = 0.2) +
  geom_line(aes(y = Y_hat, group = subject), alpha = 0.15) +
  geom_point(aes(y = accuracy), alpha = 0.1, shape = 20) +
  stat_summary(aes(y = Y_hat), geom = "line", color = "red", linewidth = 1) +
  geom_hline(yintercept = 0.5, linetype = "dashed", linewidth = 0.5) +
  coord_cartesian(ylim = c(0, 1)) +
  coord_fixed(ratio = 40)+
  theme_bw()
  ggsave(filename = "my_plot_biasp.png",width = 20,height = 20)
  
#psychometric plot for biasm

data_predictions <- read.csv("full_data_with_predictions.csv")

ggplot(data_predictions %>% filter(regression == "biasm"), aes(x = Range, y = Y_hat)) +facet_grid(rows = vars(Group), 
             cols = vars(regression,experimentname), 
             as.table = TRUE) +
  #geom_segment(aes(xend = Range, y = accuracy, yend = Y_hat), alpha = 0.2) +
  geom_line(aes(y = Y_hat, group = subject), alpha = 0.15) +
  geom_point(aes(y = accuracy), alpha = 0.1, shape = 20) +
  stat_summary(aes(y = Y_hat), geom = "line", color = "blue", linewidth = 1) +
  geom_hline(yintercept = 0.5, linetype = "dashed", linewidth = 0.5) +
  coord_cartesian(ylim = c(0, 1)) +
  coord_fixed(ratio = 40)+
  theme_bw()
  ggsave(filename = "my_plot_biasm.png",width = 20,height = 20)

 
  


```


